### ISSUE TITLE
Changes in form file not visible in the running IDE after an incremental build

### ISSUE THREAD

**Issue by ahus1** [JetBrains/gradle-intellij-plugin#1044]
**Describe the bug**
When I change a `*.form` file for the settings of my plugin, those changes are not visible in the UI when I restart the IDE using `runIde`. This happens the for the [AsciiDoc plugin](https://github.com/asciidoctor/asciidoctor-intellij-plugin). 

Workaround: delete the instrumented class `build/instrumented/org/asciidoc/intellij/settings/AsciiDocPreviewSettingsForm.class` whenever I change the form.

**To Reproduce**

1. start target `runIde`, to make the project compile and look at the plugins settings
2. change `AsciiDocPreviewSettingsForm.form`, for example change a label text (in this case, one that is in the form, not in a properties file)
3. start target `runIde` again for the incremental compile
4. look at the settings again: settings are unchanged

**Expected behavior**
When I change a form file, the instrumented class should change as well for an incremental build. 

**Environment:**

Gradle 7.3

Build time:   2021-11-09 20:40:36 UTC
Revision:     96754b8c44399658178a768ac764d727c2addb37

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.13 (Amazon.com Inc. 11.0.13+8-LTS)
OS:           Windows 10 10.0 amd64

**Additional context**

Might have been caused by the incremental instrumentation in #984. I had a look at the code changes, but wasn't able to identify what's happening there.

**Comment by hsz** [comment]
Thank you for reporting, Alexander.
Which version of the Gradle IntelliJ Plugin do you use?
Could you please verify if the issue persists in the 1.7.0-snapshot release?

**Comment by ahus1** [comment]
I'm using version 1.6 of the plugin, sorry for not putting this in the description above. Copy so much, but not the right things. 

Will give the snapshot release a try.

**Comment by ahus1** [comment]
Unfortunately it behaves the same with in 1.7.0-SNAPSHOT as in 1.6.0

**Comment by hsz** [comment]
Bummer. I'll take care of it tomorrow morning.

**Comment by hsz** [comment]
Fix is now available in the nightly build – could you please verify it once again?

**Comment by ahus1** [comment]
I had a look here https://oss.sonatype.org/content/repositories/snapshots/org/jetbrains/intellij/org.jetbrains.intellij.gradle.plugin/1.7.0-SNAPSHOT/ and the last snapshot was dated "20220629.130527-34".

Are you sure the snapshot was published? Looking at the [GitHub action run](https://github.com/JetBrains/gradle-intellij-plugin/actions/runs/2613041550) it seems that not so very much happend there.

I tried to double check the snapshot URL, but didn't find it in the docs.

**Comment by hsz** [comment]
@ahus1 You're right – my apologies. I have manually triggered the nightly release, and now a proper "35" update is available.

**Comment by ahus1** [comment]
This version looks good, I was able to test that once I change the form, the changes appear also when I then build and start the IDE incrementally.

I was curious and had a look what you changed ... and I fail to comprehend it. Good to have you to here to maintain this plugin!

**Comment by ahus1** [comment]
BTW: It would be nice to have some docs how to use the snapshot version in the main README, or a separate file.

**Comment by ahus1** [comment]
Ah, found the docs: https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#intellij-extension - assumed they would be in this repo, then I found them there.

**Comment by hsz** [comment]
Thanks for the confirmation and feedback!
In general, the problem was caused because we have switched to incremental instrumentation. Before, the instrumentation mechanism applied changes to all of the compiled classes every time it was triggered – thanks to that, your changes were always reflected.
As for now, instrumentation watches for changes in compiled Java/Kolin classes. If one is updated by the compiler (so reverted to an un-instrumented form), it handles just this specific file.
In the case of form classes, the `.form` file is loaded from the `src` directory, not `build/classes`, and the instrumentation mechanism doesn't know about updates as the `.class` file remains untouched.
With the recent change, I'm watching `src/**/*.form` files for changes, and if one is dirty, I grab the un-instrumented `.class` of that `.form`, and put it to the `build/instrumented` to make the instrumentation mechanism aware of changes.

I hope this is clear now. :D

BTW – I just added some extra pointers to the README regarding the installation of the snapshot release.
