### ISSUE TITLE
1.7.0-SNAPSHOT instrumentCode breaks Kotlin "friend" source sets

### ISSUE THREAD

**Issue by abrooksv** [JetBrains/gradle-intellij-plugin#1052]
**Describe the bug**
With 1.7.0-SNAPSHOT, Kotlin test classes can no longer call `internal` methods of the production source set if `instrumentCode` is enabled

**To Reproduce**
Have a unit test call a `internal` Kotlin method. Code will fail to compile with something along the lines of `AccountListTest.kt: (65, 26): Cannot access 'updatedCredentials': it is internal in 'AccountListModel'`

Code does compile if instrumentCode is turned off

**Expected behavior**
Code should compile

**Environment:**
 - OS: macOS
 - Gradle IntelliJ Plugin Version 1.7-SNAPSHOT (July 6th build?)
 - Gradle Version 7.4.2
 - Kotlin Gradle plugin: 1.6.20

**Additional context**

**Comment by abrooksv** [comment]
Building a minimal reproduction is making it pass, will close this to not distract you. Will re-open when/if I find out more

**Comment by cesar1000** [comment]
I ran into this issue with 1.7.0. Let me explain the reason.

The test task uses the main source set outputs as friend paths. Before running the instrumentation task, these are:

```
build/classes/java/main
build/classes/kotlin/main
build/libs/plugin.jar
```

After the instrumentation task runs, the outputs are modified like this:

```
build/instrumented/instrumentCode
libs/plugin.jar
```

The compilation classpath, however, looks like this:

```
build/classes/kotlin/main
build/instrumented/instrumentCode
```

As a result, classes from the main source set are resolved from `build/classes/kotlin/main`, which is not a friend classpath.

In my view, the issue is that the compilation classpath should not contain `build/classes/kotlin/main`. That being said, one simple hack around the issue is to ensure that the original friend paths are preserved after instrumentation:

```
tasks.compileTestKotlin {
    friendPaths.from(friendPaths.files)
}
```
