### ISSUE TITLE
Dependencies added in `build.gradle.kts` should override IDE dependencies.

### ISSUE THREAD

**Issue by YiiGuxing** [JetBrains/gradle-intellij-plugin#1060]
**Describe the bug**
The dependency added in `build.gradle.kts` is invalid when it conflicts with IDE internal dependencies, IDE still only recognizes IDEA internal dependencies. 

For example:

I added version `1.15.2` of `jgroup` to `build.gradle.kts`:
```
dependencies {
    implementation("org.jsoup:jsoup:1.15.2")
}
```

IDEA has other version of `jgroup`, when I use the related API, the IDEA recognizes the built-in version first:

![image](https://user-images.githubusercontent.com/10737066/178107268-21b44b1b-8589-4807-b3d0-a4971189cf2e.png)

This makes IDEA's behavior in code completion, prompting, etc. inconsistent with expectations.

Such as the following code:
```kotlin
Jsoup.parse(html)
    .body()
    .selectFirst(".content")
    ?.insertChildren(0, Element("div"))
```

This code will have a warning:

![image](https://user-images.githubusercontent.com/10737066/178107916-e10ffc71-68b1-4cca-a362-ff0dd525e525.png)

IDEA's suggested code is:
```kotlin
Jsoup.parse(html)
    .body()
    .selectFirst(".content")
    .insertChildren(0, Element("div"))
```

However, the suggested code may throw a `NullPointerException` at runtime, which IDEA should recognize as a compilation error:

![image](https://user-images.githubusercontent.com/10737066/178108028-f055e243-3752-40e5-94e0-75161f787dfd.png)

**To Reproduce**

**Expected behavior**
Dependencies added in `build.gradle.kts` should override IDE dependencies.

**Environment:**
 - OS: Windows 11
 - Gradle IntelliJ Plugin Version 1.7.0
 - Gradle Version 7.4.2

**Additional context**
Related iusse and post:
#656
[Class Loaders.](https://plugins.jetbrains.com/docs/intellij/plugin-class-loaders.html)

**Comment by hsz** [comment]
It turned out that there's something wrong with Gradle itself. The Gradle IntelliJ Plugin creates custom configurations that hold extra dependencies, like the `idea` configuration adds `com.jetbrains:ideaIC:222-EAP-SNAPSHOT` to your classpath.

In Gradle, if you extend one configuration with another using `extendsFrom`, and there are already more configurations inherited, they’ll be sorted alphabetically.
That means the dependencies they contain will appear in the final configuration in the same order as their containers do.

This is why `idea` (and IDEA libraries) take precedence over `implementation` configuration and dependencies you configure in the project.

I have prefixed all custom configurations with `z##_` so they'll hit the end of the list, and since now, your libraries will be considered first.
To me, this is clearly a Gradle issue – but finally, I have hunted this behavior down.

**Comment by Undin** [comment]
It seems the corresponding changes may break compilation.
For example, if you try to use `gradle-intellij-plugin` [1.8.0](https://github.com/intellij-rust/intellij-rust/pull/9164/commits/a1545695ab7fec5d2571b78236aa1d56f78e5e5f) to build IntelliJ Rust plugin using CLion as base IDE, it will [fail](https://github.com/intellij-rust/intellij-rust/runs/7718866457?check_suite_focus=true)
It seems it because CLion libs contain some old version of `jetbrains-annotations` where `Nls` doesn't have `ElementType.TYPE_USE` target and in combination with recent changes in classpath ordering, now the compilation tries to use lib from CLion instead of `org.jetbrains:annotations:23.0.0` defined by `gradle-intellij-plugin`

Moreother, if I add `implementation("org.jetbrains:annotations:23.0.0")` dependency manually to my plugin, it won't help
