### ISSUE TITLE
Plugin Verifier fails on GitHub actions if too many IDEs

### ISSUE THREAD

**Issue by abrooksv** [JetBrains/gradle-intellij-plugin#1285]
**Describe the bug**
If you have too many IDE versions (we have 16 in our full matrix) the task is appears to be downloading all the IDEs so GitHub Actions kills off the job. I presume it is due to it thinks it stalled due to no output during this process?

**To Reproduce**
Run a very large text matrix in the plugin verifier on GitHub, it should die after a few mins with no message

**Expected behavior**
Build should run, and ideally use similar download progress system as other dependencies if possible

**Environment:**
 - OS: GitHub Actions, ubuntu-latest
 - Gradle IntelliJ Plugin Version: 1.12
 - Gradle Version 7.6

**Comment by johhn11101** [comment]
[Seen]

**Comment by YannCebron** [comment]
> we have 16 in our full matrix

depending on the functionality of a plugin, some of these could possibly be omitted
e.g. "pure" Java support is the same in IJ Community vs Ultimate

possibly providing them directly instead of downloading automatically could work (https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#tasks-runpluginverifier-downloaddir)

**Comment by abrooksv** [comment]
> > we have 16 in our full matrix
> 
> depending on the functionality of a plugin, some of these could possibly be omitted e.g. "pure" Java support is the same in IJ Community vs Ultimate
> 
> possibly providing them directly instead of downloading automatically could work (https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#tasks-runpluginverifier-downloaddir)

A lot of it comes from supporting multiple major versions, I think we did collapse IU into IC, so we only worry about PY, IC, GO now so we are down to 12 (221, 222, 223, 231 EAP)

I could see us collapsing them all into IU with the Go plugin, Python plugin installed, but that doesn't look possible to do with the current gradle tasks

**Comment by hsz** [comment]
The `runPluginVerifier` task relies on the standard dependencies resolution mechanism:

https://github.com/JetBrains/gradle-intellij-plugin/blob/6b25f1b1cdfe3cd7f07034687646a45e10a204ed/src/main/kotlin/org/jetbrains/intellij/tasks/RunPluginVerifierTask.kt#L329-L349

Under the hood, the `DependenciesDownloader` creates a custom Ivy repository pointing to the JetBrains CDN and downloads IDEs into the Gradle cache.

In addition to everything, we print logs with _info_ level when starting every IDE download — so that should be enough to feed GitHub with data:

https://github.com/JetBrains/gradle-intellij-plugin/blob/6b25f1b1cdfe3cd7f07034687646a45e10a204ed/src/main/kotlin/org/jetbrains/intellij/tasks/RunPluginVerifierTask.kt#L318

**Comment by abrooksv** [comment]
> In addition to everything, we print logs with info level when starting every IDE download — so that should be enough to feed GitHub with data:
Ah, we print at lifecycle level due to verbosity of other stuff

I actually ended up splitting the verifier into parallel tasks due to the number of them which helps.

If you are using the standard Gradle downloaders then I would be fine closing this as working as intended

**Comment by hsz** [comment]
Interesting. Also, #1341 reported that parallel runs failed due to the race to download the same IDEs.
I'm about to extract downloading IDEs into a separate task that may help in caching and managing IDEs.

**Comment by abrooksv** [comment]
Ah, sorry. I meant I rub parallel GitHub actions jobs
