### ISSUE TITLE
Please mention getResource bug to the README

### ISSUE THREAD

**Issue by baron1405** [JetBrains/gradle-intellij-plugin#170]
Now that the Gradle IntelliJ plugin packages plugins as JARs developers might hit the following IntelliJ platform bug: https://youtrack.jetbrains.com/issue/IDEA-167846. It should probably be mentioned somewhere on the readme.

**Comment by zolotov** [comment]
Hi! Thank you for the issue. I'm not sure it a bug, but I let the IDEA team decide it. 

From my point of view, the issue is on IntelliJ runtime and its plugin classloader, I don't see how `gradle-intellij-plugin` is related to it. Also, I believe that `gradle-intellij-plugin` documentation should not mention all submitted bugs on IntelliJ runtime. I have no idea how to maintain that list and what the value is in it.

**Comment by baron1405** [comment]
I agree that this is not a bug in the plugin. My concern is that I uncovered this bug when upgrading from 0.1.0 to 0.2.0 because now my plugin is packaged as a JAR instead of being unpacked on the filesystem. Just wanted to alert the community that this could be an issue when they upgrade but I completely understand that you cannot and should not be a bug list mirror :-)

**Comment by zolotov** [comment]
I see. Indeed, it's worth to mention in changes. Thanks!
