### ISSUE TITLE
Would it be possible to get runIde to use the Java bundled with the IDE? 

### ISSUE THREAD

**Issue by patflynn** [JetBrains/gradle-intellij-plugin#192]
Ideally when testing locally we'd use the same Java that will be used on the end user system, which for the latest versions of IJ is usually the Java bundled with the IJ distribution.

We missed [a bug ](https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1316) in our plugin because we were testing locally with our own JDKs.

**Comment by zolotov** [comment]
Hi Patrick, 

It makes sense indeed. Until the issue is fixed, you can do this manually: use https://bintray.com/jetbrains/intellij-jdk repo for downloading JRE for your OS, unpack it and substitute executable of `runIde` task (which is `JavaExec` task under the hood) with a `java` from downloaded JRE

**Comment by patflynn** [comment]
Thanks Alexander!

**Comment by zolotov** [comment]
added the new option for setting a JBRE version:

```
runIde {
  jbreVersion 'jbrex8u152b1024.10'
}
```

Also, for IDEA > 2017.3, the version will be inferred automatically

**Comment by patflynn** [comment]
Great. Thanks!
