### ISSUE TITLE
Download ideaIC-LATEST-EAP-SNAPSHOT.zip

### ISSUE THREAD

**Issue by TomasYu** [JetBrains/gradle-intellij-plugin#199]
I use IntelliJ Platform , and it can create IntelliJ plugin, but the gradle use 

`plugins {
    id "org.jetbrains.intellij" version "0.2.9"
}`

I don't think it is necessary!  And what' more, it download 

`Download https://www.jetbrains.com/intellij-repository/snapshots/com/jetbrains/intellij/idea/ideaIC/LATEST-EAP-SNAPSHOT/ideaIC-LATEST-EAP-SNAPSHOT.zip
> Configuring > 1/1 projects > 849 KB/352.01 MB downloaded^`

It's so big! 

What should I do?

**Comment by yole** [comment]
An IntelliJ IDEA plugin depends on IntelliJ IDEA. Downloading IntelliJ IDEA is in fact necessary to build a plugin. You should wait for the downoad to complete.

**Comment by caofanCPU** [comment]
@yole 
That's a bad experience.
Every time I update IntelliJ IDEA app, then I open my gradle project, it will doload ideaIC-LATEST-EAP-SNAPSHOT.zip
Compared with the too slow network, 10~100KB/s with VPN, the 560MB zip file is still so large...
Besides, Intellij IDEA update twice or more in a month.
Once you update, even the same project, you need to wait it rebuilding file index.
Even though the features of the new version are tempting, I still can only choose to have plenty of free time to update, because the waiting time is too long

**Comment by yole** [comment]
@caofanCPU You can depend on a specific IntelliJ IDEA release or use the `alternativeIdePath` property to point to your local IDE installation.

**Comment by hsz** [comment]
@caofanCPU, as @yole said: you should specify the version explicitly to avoid such situations in the future:

```
intellij {
  version '2020.3'
}
```

Otherwise, you're always building your plugin with the latest available release, which may cause some incompatibilities when running it in previous IDE versions.
Please keep in mind that it should point to the same target version you have specified in the `sinceBuild` property.

You can read more about the Build Number Ranges [here](https://jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html).
