### ISSUE TITLE
Attach `<IDE_ROOT>/lib/src/*.zip` sources

### ISSUE THREAD

**Issue by zdary** [JetBrains/gradle-intellij-plugin#207]
Hi,

I have a question. While using gradle plugin for plugin development I chose to download sources as well. The sources are downloaded but When I navigate to a class from my plugin to a class in open-api I always end up in decompiled class instead of source code downloaded by gradle.

IDEA comes with src forlder for spring.api and a few more. Is there a way gradle pluging would attach those as sources?

**Comment by zolotov** [comment]
IntelliJ Utlimate is not open sources project. You can open only sources of classes from IntelliJ Community.

> IDEA comes with src forlder for spring.api and a few more

I don't see any src directory for spring. Spring is a close-sourced part.

**Comment by zolotov** [comment]
closing due to lack of feedback. the issue is unclear to me

**Comment by bjansen** [comment]
@zolotov the Ultimate edition comes with a few OpenAPI extensions for Ultimate plugins, in order to allow developers to contribute extensions points to these plugins I suppose. Spring is one of them, the source code for Spring's OpenAPI is located under `$IDEA_HOME$/lib/src/src_spring-openapi.zip`. This folder also contains source code for other plugins like Tomcat, persistence etc. Perhaps the gradle-intellij-plugin could automatically attach these source files to their corresponding plugins?

See this page for more info: http://www.jetbrains.org/intellij/sdk/docs/reference_guide/frameworks_and_external_apis/spring_api.html

**Comment by zolotov** [comment]
@bjansen found it, thank you!
