### ISSUE TITLE
"implementation" dependencies don't get bundled into the distribution zip

### ISSUE THREAD

**Issue by Egorand** [JetBrains/gradle-intellij-plugin#239]
We're observing this in [SQLDelight](https://github.com/square/sqldelight/issues/677), here's the [build.gradle](https://github.com/square/sqldelight/blob/master/sqldelight-studio-plugin/build.gradle). Although the config uses version `0.2.5`, I tried it with `0.2.17` and it still fails. Switching back to `compile` instead of `implementation` fixes the problem.

**Comment by szymenpl** [comment]
@zolotov Any information about the progress? Bug still occurs in latest version of plugin.

**Comment by nbransby** [comment]
Just to add to this - due to this issue: https://youtrack.jetbrains.com/issue/KT-27111 there is currently no way to include a multi-platform library in a intellij plugin

**Comment by henryju** [comment]
With Gradle 7.0, `compile` will be removed.
> The compile configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the implementation configuration instead.

**Comment by zolotov** [comment]
I investigate the commit https://github.com/cashapp/sqldelight/commit/83db4041da007297498dad8c951fb269705746f6#diff-4331df40d3e81b33c90632dd467054bfc7623fb301c984b9d254af472dea5c75.

My theory is that `implementation project(':sqldelight-compiler')` doesn't work as `sqldelight-compiler` never produces jar file on buildPlugin task. 

The possible solutions are:
- run `./gradlew :sqldelight-compiler:jar :buildPlugin`
- add something like `jar.dependsOn(":sqldelight-compiler:jar")` in the root build script
- add something like `sourceSets { main { output.dir(jar.outpuFile.asFile.get())` to `sqldelight-compiler` build script
- add `apply plug: 'java'` to `sqldelight-compiler` script

If any of this works, it seems to be the issue (or rather expected behaviour) of `java-library` plugin.
