### ISSUE TITLE
Attach source code of kotlin dependency

### ISSUE THREAD

**Issue by Undin** [JetBrains/gradle-intellij-plugin#264]
Is it possible to download the source code of transitive dependencies of IDEA?

For example, IDEA has dependency on kotlin stdlib but when you try to goto definition of anything from  it you see the following
<img width="1117" alt="screen shot 2018-02-18 at 16 41 59" src="https://user-images.githubusercontent.com/2539310/36352482-cb4aeb44-14ca-11e8-9978-6cfed581535c.png">

It's rather inconvenient, especially if all the plugin code is written on kotlin

**Comment by zolotov** [comment]
Kotlin is not transitive dependency, it's a part of IDEA dependency and IDEA dependency doesn't provide sources for it. You can create your own Kotlin dependency and use its sources.

**Comment by Undin** [comment]
Okay(

**Comment by SomeoneToIgnore** [comment]
Could you elaborate on the way it is supposed to be implemented?

I've tried the brute force approach and added the dependency as
`project.dependencies.add(JavaPlugin.RUNTIME_ONLY_CONFIGURATION_NAME, "org.jetbrains.kotlin:kotlin-stdlib:1.3.11:sources")` in the plugin and it did not change a thing.
Same happened when I've downloaded the sources locally, renamed the jar to `kotlin-stdlib-sources.jar` and added the jar directly via `project.files`.
The renaming part I've done was due to the assumption that the sources jar name should match the dependency jar name and this is the artifact we get from the intellij jar:
![screenshot 2019-01-04 at 11 20 23](https://user-images.githubusercontent.com/2690773/50681162-230d2d80-1013-11e9-8d50-09365cef54c7.png)

Overriding the Kotlin version with `project.dependencies.add(JavaPlugin.RUNTIME_ONLY_CONFIGURATION_NAME, "org.jetbrains.kotlin:kotlin-stdlib:1.3.11")` works and the sources are displayed correctly, but I have my doubts about the approach.
I'm also wondering on how we're supposed to detect which Kotlin sources to use for each Intellij version.

**Comment by zolotov** [comment]
@SomeoneToIgnore sure

> how we're supposed to detect which Kotlin sources to use for each Intellij version?

if IDEA vesrion > 2017.3, `new File(intellij.extension.ideaDependency.ivyRepositoryDirectory, 'dependency.txt')` contains version of Kotlin plugin that was used for building it.

> how we're supposed to add those sources?

`org.jetbrains.intellij.dependency.IdeaDependencyManager#getOrCreateIvyXml` generates a repo and defines sources artifact. By default it adds `ideaIC-sources.jar`. For kotlin it should add also something else. Note, that added sources should be accessible using patterns defined in `org.jetbrains.intellij.dependency.IdeaDependencyManager#register`

**Comment by fcurts** [comment]
Workaround is demonstrated here: https://github.com/google/ide-perf/blob/master/build.gradle.kts

**Comment by gharrma** [comment]
FYI @chashnikov uploaded https://github.com/JetBrains/intellij-community/commit/9fc9a59c0d to start including library sources directly in the IDEA sources archive. Presumably this will take effect starting with IJ 2021.2.
