### ISSUE TITLE
Notify about overriding any attribute in plugin.xml

### ISSUE THREAD

**Issue by zolotov** [JetBrains/gradle-intellij-plugin#284]

**Comment by hairybreeches** [comment]
I think I'm seeing this problem. My plugin.xml has the parameter 

`<idea-version since-build="162"/>`

but the output into `build/patchedPluginXmlFiles/plugin.xml` has it changed to

`<idea-version since-build="182.2949" until-build="182.*"/>`

Changing this value means that I can't run my plugin in datagrip. When I try to run datagrip using the "alternativeIdePath", I get

`WARN: pgMustard not loaded: since build 182.2949 > DB-181.5087.33`

Which is frustrating, since that's not what I wanted the `since-build` parameter to be! I _think_ that it's the gradle plugin that's substituting in 182.2949 for the `since-build` parameter - I can't find any uses at all of that version number in my project (outside the build directory).

Am I right that it's the plugin making this substitution? If so, how do I make it stop?

**Comment by zolotov** [comment]
@hairybreeches

> <idea-version since-build="162"/>

Have you really verified that your plugin works on DB 2016.1? If not, you must not do this.

> WARN: pgMustard not loaded: since build 182.2949 > DB-181.5087.33

If you want to build a plugin for DB-181.* it's highly recommended to use 181.* platform for compiling. Using 182.* platform for it and patching the `plugin.xml` is antipattern.

> Am I right that it's the plugin making this substitution?

Yes, it's stated in the README.md.

> If so, how do I make it stop?

You should not, but if you still want, please find a minute to read the README.md, couple ways described are described there.
