### ISSUE TITLE
Install plugin dependencies transitive dependencies automatically for tests.

### ISSUE THREAD

**Issue by JakeWharton** [JetBrains/gradle-intellij-plugin#38]
Currently I have to list not only the plugins I depend on, but their transitive dependencies as well.

**Comment by zolotov** [comment]
Any example? What kind of transitive dependencies of what plugin?

**Comment by JakeWharton** [comment]
Sure. I'm depending on the android plugin which depends on junit and groovy and groovy depends on gradle.

**Comment by JakeWharton** [comment]
When I use `runIdea` it seems to work automatically (presumably from the `plugin.xml`'s `<dependency>` declaration) but when I run `test` I seem to have to specify them all explicitly in the `plugins` section of the Gradle config.

**Comment by zolotov** [comment]
I see. Well, I think it's possible to implement, but I don't think that it's worth it. Implementing of brittle and slow dependency resolution strategy for packed plugins doesn't look better than just writing
```
plugins 'andriod', 'junit', 'gradle', 'Groovy'
```

**Comment by JakeWharton** [comment]
Yeah it's not _overly_ terrible to specify them all. I just don't like having to encode implementation details of other plugins into my build and having their dependency changes end up breaking my build.

**Comment by zolotov** [comment]
>  having their dependency changes end up breaking my build.

They're dependencies, explicitly or implicitly dependencies always do this :) No matter whether you defined them in build.gradle or not. 

I keep this issue open and will think about it, but as I said before I'm very skeptical about this.

**Comment by JakeWharton** [comment]
By that argument, should be specify them all in the `plugin.xml`. I'm happy to change my argument to the disconnect between those beahviors if it will help convince you!

**Comment by zolotov** [comment]
I agree that the feature you suggested is how it *should* work but it's more about efforts and benefits.

How I can see the implementation of this:
For each gradle initialization the plugin will go to each jar in IDEA SDK, look for xml files, parse them and extracting its ids.
Then it will go though all attached jar, look for xml file, look for depends tags, resolve dependency ids, look for other files, try to avoid loops.
Looks slowly for each initialization, right?
Ok then, I'll make a cache for each SDK, I will try to make proper cache invalidation. And will fail apparently :)

Then it will turn out that it doesn't work for some plugins, because xml files also might include other xml files, so the plugin have to resolve them too somehow. And it's not easy either because included xml can be out of the current jar and I don't really understand the resolution rules for such cases yet.

To me it looks like a lot of things to do. So the point is that here is something to think before doing all this stuff in order to make `build.gradle` shorter for 3 words which you will change twice a year.

**Comment by zolotov** [comment]
Btw, could you create a simple project to recreate the issue with tests? Maybe I'll find a simpler way to fix it.

**Comment by Turbo87** [comment]
You can use the `handlebars-gradle` branch in https://github.com/Turbo87/intellij-plugins/ for this. It depends on the `JavaScriptLanguage` plugin, but also needs the `CSS` plugin as a transitive dependency. You can test this by removing the `CSS` dependency from the `build.gradle` file and then running `./gradlew test`.

**Comment by yigit** [comment]
I'm having a similar problem when I try to compile a plugin that depends on Android Studio 3.1.0-alpha06 I'm not sure what plugin to add to my build.gradle file because I cannot find a smali plugin in the jetbrains repo.

**Comment by yigit** [comment]
nevermind, adding lowercase `smali` seems to work.

**Comment by masooh** [comment]
I had the same problem with the transitive Groovy properties dependency: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360007758740-How-can-I-write-a-test-for-a-plugin-editing-Groovy-files-. I don't mind in adding transitive dependencies, the problem for me was to find out that this is my problem. How should I figure out, that the properties plugin is missing if my Groovy file is recognized as plain text. In my opinion it's not important that tests have a dependency resolution (although it would be nice), but the Groovy plugin should fail and not just silently do anything else.

**Comment by zolotov** [comment]
implemented for builtin plugins
