### ISSUE TITLE
Integrate intellij-plugin-verifier

### ISSUE THREAD

**Issue by breandan** [JetBrains/gradle-intellij-plugin#385]
It would be nice if there was some kind of integration with the [intellij-plugin-verifier](https://github.com/JetBrains/intellij-plugin-verifier) to detect potential compatibility issues before the plugin is published. @serejke

**Comment by bjansen** [comment]
Until this feature is added, it is possible to run the verifier as a regular Gradle task, as I did in one of my plugins:

https://github.com/bjansen/pebble-intellij/commit/72f3823f7b3dec7552e0dc15893057e2239edace

Replace `"build/distributions/pebble-intellij.zip"` with your actual distribution path, and configure extra IDEs to verify in `gradle.properties`:

```properties
pluginVerifierIdes=/Applications/WebStorm.app/Contents/,/Applications/IntelliJ IDEA CE.app/Contents/
```

**Comment by zolotov** [comment]
@bjansen the task runs the verification using the very same IDEA that you use for building plugin, right? What's the point? What kind of incompatibilities do you want to find there?

**Comment by bjansen** [comment]
You can add other IDEs in the `pluginVerifierIdes` property, as I explained in my previous comment.
But you're right about the IDE used for building the plugin, perhaps I shouldn't add it to the list of IDEs to be tested.

**Comment by zolotov** [comment]
Got it. Well, if the plugin will download different IDE version to check, I'd prefer real testing against different IDEs, than just running verifier.

Related issue: https://github.com/JetBrains/gradle-intellij-plugin/issues/324.

**Comment by bjansen** [comment]
Well the verifier can verify against non-Java IDEs. The verifier will hopefully soon be able to [detect missing optional dependencies](https://youtrack.jetbrains.com/issue/MP-1735) to avoid reporting false positives

If you run unit tests on the same non-Java IDEs, some will fail because features used in optional dependencies are missing, which will lead to false positives.

**Comment by zolotov** [comment]
Makes sense. Thank you for details

**Comment by FWDekker** [comment]
I've written [a workaround for this problem in my Randomness plugin](https://github.com/FWDekker/intellij-randomness/pull/262/files).

The _good_ part is that it will download the IDEs for you, so you don't have to pre-install them somewhere. Just copy the task from the link above, configure it (see below), and run it. That's it. This way, you don't have any OS-dependent paths in your configuration anywhere, and other people can replicate it without having to follow complicated instructions.

The _bad_ part is that it stores the IDEs in a directory of your choice. A much better solution would be to store them in the Maven cache (which is already where the Gradle IntelliJ plugin stores them), but I couldn't figure out an easy way to do that.

---

You can configure it as follows:
```groovy
runPluginVerifier {
    /// Required params
    // Name of the zip of your plugin in `build/distributions` (without `.zip`)
    pluginFileName = "intellij-randomness-$version"
    // The IDEs you want to verify against
    ides = ["idea-ideaIC-2018.1", "clion-clion-2019.3"]

    /// Optional params
    // Where to store the IDEs
    // Warning: If it's in build/, `gradle clean` will wipe the cache.
    ideCacheDir = file("$buildDir/ides/")
    // Whether to download the IDEs even if they're already in cache
    forceUpdateIdes = false
    // The version of the verifier plugin to use
    verifierVersion = "1.222"
}
```

**Comment by bjansen** [comment]
> A much better solution would be to store them in the Maven cache (which is already where the Gradle IntelliJ plugin stores them)

Perhaps you could use [IdeaDependencyManager](https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/main/groovy/org/jetbrains/intellij/dependency/IdeaDependencyManager.groovy)? Although it looks like it's adding a dependency to the project, which might not be what we want.

**Comment by FWDekker** [comment]
> Perhaps you could use IdeaDependencyManager?

When I tried that I mistakenly believed it was a non-public class because IntelliJ couldn't import it. Manually writing the import works though, so I'll see if I can figure something out. It looks like I can set `configureDefaultDependencies` to `false` in the `IntelliJPluginExtension` to prevent it from adding dependencies.

**Comment by FWDekker** [comment]
I've updated the script by copying the essential parts of the `IdeaDependencyManager` into the script (which is only a few lines anyway). Like the manager, the dependency is added to a separate, detached configuration, so it won't bloat your distribution files.

I don't really plan on expanding or improving it much further because it is, after all, only a _workaround_ for a problem that is much better solved by integrating it into the Gradle IntelliJ plugin.

**Comment by rachelcarmena** [comment]
Thanks @YannCebron for letting me know about this issue :raised_hands: 

I just included in `build.gradle`:

```
apply from:'https://raw.githubusercontent.com/FWDekker/intellij-randomness/master/gradle/scripts/verifier.gradle'

runPluginVerifier {
    pluginFileName = "<name>-<version>"
    ides = ["IC-2019.3.5"]
    verifierVersion = "1.241"
}
```

Then:

```
./gradlew runPluginVerifier
```

it works like a charm. Thanks @FWDekker :clap:

**Comment by hsz** [comment]
Integration with [IntelliJ Plugin Verifier](https://github.com/JetBrains/intellij-plugin-verifier) is now available through the `runPluginVerifier` task.

Check the [Plugin Verifier DSL](https://github.com/JetBrains/gradle-intellij-plugin#plugin-verifier-dsl) README section for more details.

**Comment by FWDekker** [comment]
Awesome, @hsz!

Accordingly, I think it's time to deprecate my workaround script. Because some projects import the script directly from my repository, I will leave the script untouched for one year, but will remove it after that. I have [added a notice of deprecation](https://github.com/FWDekker/intellij-randomness/commit/2bfad565d6c63a36f5d96b705f999cf67804a6c1) when you run my `runPluginVerifier` task. Best I could think of was adding a `println`; no idea how to add a formal deprecation notice in Gradle. (Does anyone else know?)

### [verifier.gradle](https://github.com/FWDekker/intellij-randomness/blob/2bfad565d6c63a36f5d96b705f999cf67804a6c1/gradle/scripts/verifier.gradle) will be removed from the [intellij-randomness](https://github.com/FWDekker/intellij-randomness) repository on 2021-10-29.
Meanwhile, I will no longer fix bugs or add features to my script.

**Comment by hsz** [comment]
Thanks, @FWDekker - that's a nice move. You may try with `logger.warn()`.
Then - when you'll decide to shut down that script, simply throw an exception instead of removing it.

Thanks for your work, Felix!

**Comment by FWDekker** [comment]
@hsz Good idea! I've replaced it with a `logger.warn`. I'll probably throw an exception instead of removing the script once I delete it, though I do plan on removing it entirely eventually.
