### ISSUE TITLE
Adjust log levels

### ISSUE THREAD

**Issue by Turbo87** [JetBrains/gradle-intellij-plugin#43]
It looks like IntelliJ is using log4j internally for logging and it would probably make sense to reuse it for logging in the plugins too. What I haven't been able to figure out though is how to adjust/set the log level for my plugin.

At the moment only `warn()` and `error()` actually print something to the console, but during development I would like to enable `info()` and `debug()` for my plugin classes too.

Is there a way to do this manually and if so, could you add some sort of option for that in the plugin too?

**Comment by zolotov** [comment]
> What I haven't been able to figure out though is how to adjust/set the log level for my plugin.

It's not configurable. At least it's not configurable in easy way. You can reimplement com.intellij.idea.LoggerFactory and set new factory for Logger, but I think you just need a log in run configuration instead of editing logging options. I've filed an issue about it: https://youtrack.jetbrains.com/issue/IDEA-149108

**Comment by Turbo87** [comment]
cool, thanks

**Comment by zolotov** [comment]
https://youtrack.jetbrains.com/issue/IDEA-149108 is fixed, since 2016.2.1 you'll be able to configure log file in Gradle run configuration
