### ISSUE TITLE
Migrate from jcenter and bintray usages

### ISSUE THREAD

**Issue by zolotov** [JetBrains/gradle-intellij-plugin#594]
direct dependencies

- [x] https://dl.bintray.com/jetbrains/intellij-plugin-service
- [x] https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-third-party-dependencies

in-plugin dependencies

- [ ] jbr, IntelliJPlugin (https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-jdk and https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-jbr)
- [x] verifier, IntelliJPlugin and RunPluginVerifierTask (https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-plugin-service)
- [x] UI tests, DownloadRobotServerPluginTask
- [x] javac2, IntelliJInstrumentCodeTask

**Comment by zolotov** [comment]
cc @hsz @nizienko

**Comment by hsz** [comment]
Plugin Verifier has been moved to Space Packages since v1.255: https://github.com/JetBrains/intellij-plugin-verifier/releases/tag/v1.255

- [ ] `RunPluginVerifierTask.resolveVerifierPath` (https://github.com/JetBrains/gradle-intellij-plugin/blob/8db2f85afb3285024ccefd02ff6c9c2853f8915f/src/main/groovy/org/jetbrains/intellij/tasks/RunPluginVerifierTask.groovy#L569) should switch from the `IntelliJPlugin.DEFAULT_INTELLIJ_PLUGIN_SERVICE` to the Space Packages.
- [ ] Resolving the latest version available should be updated – i.e. to use https://packages.jetbrains.team/maven/p/intellij-plugin-verifier/intellij-plugin-verifier/org/jetbrains/intellij/plugins/verifier-cli/maven-metadata.xml
- [ ] we should warn about PV versions not available in the Space Packages: <1.255 – if manually specified by the user using `verifierVersion`
