### ISSUE TITLE
List of available version

### ISSUE THREAD

**Issue by winterDroid** [JetBrains/gradle-intellij-plugin#61]
Is there somewhere a list of all versions that can be used?
I just tried for example version `IC-14.0.4` which seems to be not available.

**Comment by zolotov** [comment]
Hi, the full list of available versions you can find at https://www.jetbrains.com/intellij-repository/releases and https://www.jetbrains.com/intellij-repository/snapshots.

Indeed, there are problems with 14.0.4 because sources archive is missing, I'll fix the plugin for this case, thank you for report.

**Comment by zolotov** [comment]
0.0.38 is published
