### ISSUE TITLE
can't access https://api.bintray.com/packages/jetbrains/intellij-plugin-service/intellij-plugin-verifier/versions/_latest (403)

### ISSUE THREAD

**Issue by tbm98** [JetBrains/gradle-intellij-plugin#627]

**Comment by hsz** [comment]
@tbm98, thanks for reporting. The issue was caused by the Bintray outage: http://status.sdkman.io/incidents/fch98s3l5z3r?u=r7g886z3jjdm
It's back online again. Anyway, we've switched to the Space Packages with 890c09f commit, so since the next release, we'll not depend on Bintray regarding the Plugin Verifier.

**Comment by tbm98** [comment]
Thank you :D
