### ISSUE TITLE
Support for Build Cache for test tasks

### ISSUE THREAD

**Issue by abrooksv** [JetBrains/gradle-intellij-plugin#704]
In 0.7.3 (I have not tested on 1.x), the Test task is not cacheable.

Output form a build scan:
```
Cache key | a4ee23ff7c40bfa8fd3d5d1afe555765 |
Not cacheable | Overlapping  outputs: Gradle does not know how file  'build/idea-sandbox/config-test/options' was created (output property  '$2'). 
Task output caching requires exclusive access to output paths to  guarantee correctness (i.e. multiple tasks are not allowed to produce  output in the same location
```

**Comment by hsz** [comment]
That's _expected_, because [v1.0](https://github.com/JetBrains/gradle-intellij-plugin/releases/tag/v1.0) has introduced Configuration Cache support (and many more).
We've also covered that with tests – all of our tasks are verified if `--configuration-cache` works properly:
https://github.com/JetBrains/gradle-intellij-plugin/blob/master/src/test/kotlin/org/jetbrains/intellij/tasks/BuildPluginTaskSpec.kt#L390-L411

**Comment by abrooksv** [comment]
Does configuration cache imply that remote build cache is supported? I haven

**Comment by abrooksv** [comment]
Looks like #699 will address this

**Comment by hsz** [comment]
Did you men #705 ?

**Comment by abrooksv** [comment]
> Did you men #705 ?

Yes...yes I did :(
