### ISSUE TITLE
runPluginVerifier doesn't resolve latest EAP versions (maybe due to caching)

### ISSUE THREAD

**Issue by ahus1** [JetBrains/gradle-intellij-plugin#848]
In my plugin's setup, I added `2021.3` to run the verifier against the latest EAP release.

Looking at my build logs, I found that it cached an old EAP version and never updated it (IC-213.3714.440 in my case).

As a workaround (or solution?) I now specify the EAP build using IC-213.5744.202 in the properties (see https://github.com/asciidoctor/asciidoctor-intellij-plugin/commit/8c70059103a97c0feea83b27d4f928b7d71a5c69). 

How should this be used, and how is it supposed to work regarding EAP versions?

**Comment by YannCebron** [comment]
from https://github.com/JetBrains/gradle-intellij-plugin/#plugin-verifier-dsl:
Check the available build versions on https://jb.gg/intellij-platform-builds-list

**Comment by ahus1** [comment]
Hi @YannCebron - I didn't need to specify the exact build number of EAP versions, It worked, and it downloaded the EAP version available at that time. 

As it was caching the information, it then didn't update the download when new EAP versions became available, and eventually the real release was available. It still "seemed" to work, but used an old version. 

That was confusing. I can now avoid it by always specifying the build number. Once I specify a release number of an EAP, my local cache is "polluted" with a previous download.

**Comment by rickclephas** [comment]
I just noticed a cache issue with EAP versions as well.

Using the following configuration:
```kotlin
intellij {
    version = "233-EAP-SNAPSHOT"
    type = "IC"
}

tasks {
    patchPluginXml {
        sinceBuild = "233"
        untilBuild = "233.*"
    }

    runPluginVerifier {
        // Don't set the ideVersions, but let listProductsReleases provide them
    }
}
```

This results in the `listProductsReleases` generating the following `listProductsReleases.txt`:
```
IC-2023.3
```

As a result the plugin verifier will cache `IC-2023.3` instead of e.g. `IC-233.9102.97`.
This is fixed once you manually specify the `ideVersions` with a full build number.

Wouldn't it make sense to output the build number instead of the build version for non-release builds?
