### ISSUE TITLE
IntelliJ cannot find classes and packages using plugin version 1.3.0

### ISSUE THREAD

**Issue by DenWav** [JetBrains/gradle-intellij-plugin#850]
Relates to #801
I mentioned this in [this](https://github.com/JetBrains/gradle-intellij-plugin/issues/801#issuecomment-974587935) comment, but the issue was closed so I don't think it got any visibility.

I am using IntelliJ 2021.3, and the issue happened on all of the 2021.3 Release Candidates as well.

I think this could be an IntelliJ bug, but since this is only happening for this plugin, I think it might be something related to how it works. 

Another thing that happens now is when I try to set the version back to `1.2.0` or `1.1.3` I get this error after the Gradle import:
```
Task 'setupDependencies' not found in root project 'MinecraftDev'.
```

And there is nothing I can do to stop the error - unless maybe I created an empty task with that name, but I don't know why IntelliJ is calling that task in the first place, that is not defined anywhere that I can see.

So currently I am unable to use any plugins, the older versions that worked don't work with IntelliJ anymore, and the current version which does causes IntelliJ to not see most of the classes in the IntelliJ API. Building from the command line has no issues.

**Comment by DenWav** [comment]
And additionally I have deleted the `.gradle` and `.idea` directories, restarted IntelliJ, run the new `Repair IDE` action, invalidated caches and restarted, refreshed Gradle dependencies (`--refresh-dependencies`), restarted the Gradle Daemon, none of it helps, it always results in the same identical result.

**Comment by hsz** [comment]
@DenWav, the `setupDependencies` task was introduced with `1.3.0`, and after applying the plugin, it is added automatically to the _Task Activation_, _After Sync_ section to get all required dependencies by the IDE.
The reason for that is you don't need them when running Gradle via CLI, i.e. `./gradlew help` task. 
Previously, even the `help` task was fetching the IDE – so that's an improvement. However, when downgrading the Gradle IntelliJ Plugin version, such a task isn't available anymore – and you'll have to remove it for the mentioned configuration.

<img width="632" alt="image" src="https://user-images.githubusercontent.com/108333/144385826-5efccb57-5797-477d-8151-4cf164aa5711.png">
<img width="470" alt="image" src="https://user-images.githubusercontent.com/108333/144386448-2f6b2c8b-6091-4c87-8c75-025ce62e3628.png">

Regarding the issue itself – I'll check what's going on in there.

**Comment by hsz** [comment]
@DenWav Is this ticket still valid?

**Comment by DenWav** [comment]
Let me try upgrading and see what happens.
